import './styles/main.css';
import { createApp } from './App.js';

createApp(document.getElementById('app'));

// Register the PWA service worker (auto-generated by vite-plugin-pwa at build time).
if ('serviceWorker' in navigator) {
  import('virtual:pwa-register').then(({ registerSW }) => {
    registerSW({
      immediate: true,
      onRegisteredSW(_url, registration) {
        if (!registration) return;
        // registerSW() only ever checks for an update once, right on this
        // page load. On a standalone/home-screen PWA that isn't enough —
        // reopening the app doesn't reliably trigger a fresh check the way
        // loading an ordinary tab does, so a stale install can otherwise
        // sit there indefinitely no matter how many times you reload.
        // Explicitly re-check whenever the app becomes visible again
        // (covers "reopen from home screen"), plus a periodic fallback
        // for long-running sessions.
        document.addEventListener('visibilitychange', () => {
          if (document.visibilityState === 'visible') registration.update();
        });
        setInterval(() => registration.update(), 30 * 60 * 1000);
      },
    });
  });
}
