import './styles/main.css';
import { createApp } from './App.js';

createApp(document.getElementById('app'));

// Register the PWA service worker (auto-generated by vite-plugin-pwa at build time).
if ('serviceWorker' in navigator) {
  import('virtual:pwa-register').then(({ registerSW }) => {
    registerSW({ immediate: true });
  });
}
